# Generated by Django 2.0.2 on 2018-04-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180419_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=0, upload_to='teacher/%Y%m', verbose_name='头像'),
        ),
    ]
