# Generated by Django 2.0.2 on 2018-04-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_teacher_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='clink_nums',
            new_name='click_nums',
        ),
    ]
