# Generated by Django 2.0.2 on 2018-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('easy', '初级'), ('middle', '中级'), ('height', '高级')], max_length=10, verbose_name='难度'),
        ),
    ]
