# Generated by Django 2.0.2 on 2018-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=0, verbose_name='学习时长（分钟数）'),
        ),
    ]
